# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_auth_social',
            field=models.BooleanField(default=True),
        ),
    ]
