# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_auth_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_auth_social',
        ),
    ]
